SELECTORS: dict[str, dict] = {
    "react": {
        "login_page":         "[data-testid=login-page]",
        "login_email":        "[data-testid=login-email]",
        "login_password":     "[data-testid=login-password]",
        "login_submit":       "[data-testid=login-button-visible]",
        "home_page":          "[data-testid=home-page]",
        "nav_products":       "[data-testid=navbar-products]",
        "nav_cart":           "[data-testid=navbar-cart]",
        "cart_counter":       "[data-testid=cart-counter]",
        "nav_login":          "[data-testid=navbar-login]",
        "logout":             "[data-testid=navbar-logout]",
        "product_card":       ".product-card",
        "add_to_cart":        ".product-card button.button-primary",
        "cart_page":          "[data-testid=cart-page]",
        "cart_item":          "[data-testid=cart-item]",
        "cart_item_name":     "[data-testid=cart-item-name]",
        "cart_item_quantity": "[data-testid=cart-item-quantity]",
        "cart_item_subtotal": "[data-testid=cart-item-subtotal]",
        "decrease_quantity":  "[data-testid=decrease-quantity]",
        "increase_quantity":  "[data-testid=increase-quantity]",
        "remove_item":        "[data-testid=remove-item-button]",
        "clear_cart":         "[data-testid=clear-cart-button]",
        "empty_cart":         "[data-testid=empty-cart]",
        "cart_total":         "[data-testid=cart-total]",
        "loading_state":      "[data-testid=loading-state]",
    },
    "angular": {
        "login_page":         "[data-testid=page-login]",
        "login_email":        "[data-testid=login-email]",
        "login_password":     "[data-testid=login-password]",
        "login_submit":       "[data-testid=login-submit]",
        "home_page":          "[data-testid=page-home]",
        "nav_products":       "[data-testid=header-products]",
        "nav_cart":           "[data-testid=sidebar-cart]",
        "cart_counter":       "[data-testid=sidebar-cart]",
        "nav_login":          "[data-testid=header-login]",
        "logout":             "[data-testid=header-logout]",
        "product_card":       "[data-testid^=catalog-item-]",
        "add_to_cart":        ".catalog-card .add",
        "cart_page":          "[data-testid=page-cart]",
        "cart_item":          "car-item s-",
        "cart_item_name":     ".cart-label",
        "cart_item_quantity": None,
        "remove_item":        "[data-testid^=cart-remove-]",
        "clear_cart":         "[data-testid=cart-clear]",
        "empty_cart":         "[data-testid=empty-cart]",
        "cart_total":         None,
        "loading_state":      None,
    },
    "svelte": {
        "login_page":         ".login-shell",
        "login_email":        "input[type=email]",
        "login_password":     "input[type=password]",
        "login_submit":       "button[type=submit]",
        "home_page":          ".page-shell",
        "nav_products":       "a[href='/products']",
        "nav_cart":           "a[href='/cart']",
        "cart_counter":       "a[href='/cart'] strong",
        "nav_login":          "a[href='/login']",
        "logout":             "button:has-text('Logout')",
        "product_card":       ".product-card",
        "add_to_cart":        ".product-card button",
        "cart_page":          ".cart-page",
        "cart_item":          ".cart-pill.s-h3e7SZQrEEpL",
        "cart_item_name":     ".item-details h2",
        "cart_item_quantity": ".item-controls span",
        "remove_item":        ".remove-button",
        "empty_cart":         ".empty-cart"
    },
}
