[pytest]
testpaths = tests
markers =
    base: Tests that use the base locator strategy CSS selectors
    getby: Tests based on semantic selectors and get_by methods
addopts = 
    -v 
    -m 
    --html=reports/report.html
    --self-contained-html
    --junitxml=reports/report.xml
